## build
FROM node:18-alpine as builder

RUN apk update

WORKDIR /app

COPY . .

RUN npm install

RUN npm run build

## prod
FROM nginx:latest

## js & css
COPY --from=builder /app/public /var/www/html/public

## nginx config file
COPY /nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80